app_commande:
    resource: "@AppBundle/Controller/CommandeController.php"
    type:     annotation

app_commande:
    resource: "@AppBundle/Controller/CommandeController.php"
    type:     annotation

app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

users:
    type:     rest
    resource: AppBundle\Controller\UserController
produits:
    type:     rest
    resource: AppBundle\Controller\ProduitController




